In [2]:
import pandas as pd
import numpy as np

In [3]:
market={
    "vegetables": ["beetroot","carrot","tomato","Kovakkai","coconut"]
     , "color":["purple","orange","red","green","white"], 
     "unit":["1kg","1kg","1kg","1kg","1piece"],
     "min":[15,25,53,30,68],
     "max":[45,50,95,50,43],
    }

In [4]:
df=pd.DataFrame(market)

In [5]:
df

  vegetables   color    unit  min  max
0   beetroot  purple     1kg   15   45
1     carrot  orange     1kg   25   50
2     tomato     red     1kg   53   95
3   Kovakkai   green     1kg   30   50
4    coconut   white  1piece   68   43

In [6]:
# adding and removing

In [7]:
df.loc[5]={
    "vegetables":"Cabbage","color":"green","unit":"1piece","min":10,"max":30
}

In [8]:
df

  vegetables   color    unit  min  max
0   beetroot  purple     1kg   15   45
1     carrot  orange     1kg   25   50
2     tomato     red     1kg   53   95
3   Kovakkai   green     1kg   30   50
4    coconut   white  1piece   68   43
5    Cabbage   green  1piece   10   30

# How to drop rows and coloumns
### axis=0 it is a row
### axis=1 it is a coloumn

In [9]:
df.drop([5],axis=0)

  vegetables   color    unit  min  max
0   beetroot  purple     1kg   15   45
1     carrot  orange     1kg   25   50
2     tomato     red     1kg   53   95
3   Kovakkai   green     1kg   30   50
4    coconut   white  1piece   68   43

# checking null values
## isna(),fillna(),

In [10]:
df

  vegetables   color    unit  min  max
0   beetroot  purple     1kg   15   45
1     carrot  orange     1kg   25   50
2     tomato     red     1kg   53   95
3   Kovakkai   green     1kg   30   50
4    coconut   white  1piece   68   43
5    Cabbage   green  1piece   10   30

In [11]:
df.isna().sum()

vegetables    0
color         0
unit          0
min           0
max           0
dtype: int64

In [12]:
df.loc[4,"min"]=np.nan

In [13]:
print(df)
print()
print(df.fillna(False))

  vegetables   color    unit   min  max
0   beetroot  purple     1kg  15.0   45
1     carrot  orange     1kg  25.0   50
2     tomato     red     1kg  53.0   95
3   Kovakkai   green     1kg  30.0   50
4    coconut   white  1piece   NaN   43
5    Cabbage   green  1piece  10.0   30

  vegetables   color    unit    min  max
0   beetroot  purple     1kg   15.0   45
1     carrot  orange     1kg   25.0   50
2     tomato     red     1kg   53.0   95
3   Kovakkai   green     1kg   30.0   50
4    coconut   white  1piece  False   43
5    Cabbage   green  1piece   10.0   30

In [14]:
df.fillna(False,inplace=True)

In [15]:
df

  vegetables   color    unit    min  max
0   beetroot  purple     1kg   15.0   45
1     carrot  orange     1kg   25.0   50
2     tomato     red     1kg   53.0   95
3   Kovakkai   green     1kg   30.0   50
4    coconut   white  1piece  False   43
5    Cabbage   green  1piece   10.0   30

# LAMBDA FUNCTIONS

### Apply lambda #####     syntax:DataFrame[col].apply(lambda x:x+5)

In [16]:
df["min"]=df["min"].apply(lambda x:x+5)

In [17]:
df

  vegetables   color    unit   min  max
0   beetroot  purple     1kg  20.0   45
1     carrot  orange     1kg  30.0   50
2     tomato     red     1kg  58.0   95
3   Kovakkai   green     1kg  35.0   50
4    coconut   white  1piece   5.0   43
5    Cabbage   green  1piece  15.0   30

In [18]:
print("sum",df["min"].sum())
print("count:",df["min"].count())

sum 163.0
count: 6

In [19]:
df["min"].max()

58.0

In [20]:
df["min"].min()

5.0

In [21]:
df["min"].mean()

27.166666666666668

In [22]:
df.groupby("unit").sum()

          min  max
unit
1kg     143.0  240
1piece   20.0   73

In [23]:
df.groupby(["unit","max"]).sum()

             min
unit   max
1kg    45   20.0
       50   65.0
       95   58.0
1piece 30   15.0
       43    5.0

In [24]:
market1={
    "vegetables": ["beetroot","carrot","tomato","Kovakkai","coconut"]
     , "color":["purple","orange","red","green","white"], 
     "unit":["1kg","1kg","1kg","1kg","1piece"],
     "min":[15,25,53,30,68],
     "max":[45,50,95,50,43],
    }

In [25]:
df2=pd.DataFrame(market1)

In [26]:
df2

  vegetables   color    unit  min  max
0   beetroot  purple     1kg   15   45
1     carrot  orange     1kg   25   50
2     tomato     red     1kg   53   95
3   Kovakkai   green     1kg   30   50
4    coconut   white  1piece   68   43

In [27]:
pd.concat([df,df2],axis=1)

  vegetables   color    unit   min  max vegetables   color    unit   min   max
0   beetroot  purple     1kg  20.0   45   beetroot  purple     1kg  15.0  45.0
1     carrot  orange     1kg  30.0   50     carrot  orange     1kg  25.0  50.0
2     tomato     red     1kg  58.0   95     tomato     red     1kg  53.0  95.0
3   Kovakkai   green     1kg  35.0   50   Kovakkai   green     1kg  30.0  50.0
4    coconut   white  1piece   5.0   43    coconut   white  1piece  68.0  43.0
5    Cabbage   green  1piece  15.0   30        NaN     NaN     NaN   NaN   NaN

In [28]:
students=pd.read_csv("datasets/Stuaddiction.csv")

In [29]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 705 entries, 0 to 704
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    705 non-null    int64
 1   Age                           705 non-null    int64
 2   Gender                        705 non-null    object
 3   Academic_Level                705 non-null    object
 4   Country                       705 non-null    object
 5   Avg_Daily_Usage_Hours         705 non-null    float64
 6   Most_Used_Platform            705 non-null    object
 7   Affects_Academic_Performance  705 non-null    object
 8   Sleep_Hours_Per_Night         705 non-null    float64
 9   Mental_Health_Score           705 non-null    int64
 10  Relationship_Status           705 non-null    object
 11  Conflicts_Over_Social_Media   705 non-null    int64
 12  Addicted_Score                705 non-null    int64
dtypes: float64(2), int64(5), object(6)
memory usage: 71.7+ KB

In [30]:
students.describe()

,Student_ID,Age,Avg_Daily_Usage_Hours,Sleep_Hours_Per_Night,Mental_Health_Score,Conflicts_Over_Social_Media,Addicted_Score
count,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000
mean,353.000000,20.659574,4.918723,6.868936,6.226950,2.849645,6.436879
std,203.660256,1.399217,1.257395,1.126848,1.105055,0.957968,1.587165
min,1.000000,18.000000,1.500000,3.800000,4.000000,0.000000,2.000000
25%,177.000000,19.000000,4.100000,6.000000,5.000000,2.000000,5.000000
50%,353.000000,21.000000,4.800000,6.900000,6.000000,3.000000,7.000000
75%,529.000000,22.000000,5.800000,7.700000,7.000000,4.000000,8.000000
max,705.000000,24.000000,8.500000,9.600000,9.000000,5.000000,9.000000

In [31]:
students.count()

Student_ID                      705
Age                             705
Gender                          705
Academic_Level                  705
Country                         705
Avg_Daily_Usage_Hours           705
Most_Used_Platform              705
Affects_Academic_Performance    705
Sleep_Hours_Per_Night           705
Mental_Health_Score             705
Relationship_Status             705
Conflicts_Over_Social_Media     705
Addicted_Score                  705
dtype: int64